config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'shows/index'
  get 'shows/new'
  post 'shows',              to:"shows#create"

  get 'documentaryfilms/index'
  get 'documentaryfilms/new'
  post 'documentaryfilms',   to:"documentaryfilms#create"

  get 'movies/index'
  get 'movies/new'
  post 'movies',             to:"movies#create"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/show.rb
class Show < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentaryfilms_controller.rb
class DocumentaryfilmsController < ApplicationController
  def index
    @documentaryfilms = Documentaryfilm.all
  end

  def new
    @documentaryfilm = Documentaryfilm.new 
  end

  def create
    @documentaryfilm = Documentaryfilm.new(documentaryfilms_params)
    
    if @documentaryfilm.save
      redirect_to documentaryfilms_index_path      
    else
      render :new
    end 
  end

  private 
  def documentaryfilms_params
    params.require(:documentaryfilm).permit(:name, :synopsis, :director)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new 
  end

  def create
    @movie = Movie.new(movies_params)
    
    if @movie.save
      redirect_to movies_index_path      
    else
      render :new
    end 
  end

  private 
  def movies_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end 
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end

  def new
    @show = Show.new 
  end

  def create
    @show = Show.new(shows_params)
    
    if @show.save
      redirect_to shows_index_path      
    else
      render :new
    end 
  end

  private 
  def shows_params
    params.require(:show).permit(:name, :synopsis, :director)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilms_helper.rb
module DocumentaryfilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/documentaryfilms/index.html.erb
<h1>Mostrando todos los Documentales</h1>
<p>Cantidad de documentales: <%= @documentaryfilms.count %></p>

<% @documentaryfilms.each do |documentaryfilm| %>
    <h3><%= documentaryfilm.name %></h3>
    <h3><%= documentaryfilm.synopsis %></h3>
    <h3><%= documentaryfilm.director %></h3>
<% end %>

<div>
    <%= link_to "Agregar nuevo Documental", documentaryfilms_new_path, class:"btn btn-dark" %>
</div>

app/views/documentaryfilms/new.html.erb
<h1 class="text-center my-5">Crear Documental</h1>
<br><br>

<div class="d-flex justify-content-center">
    <div class="card col-6">
        <%= form_with model: @documentaryfilm, method: :post do |documentaryfilm| %>
            <div class="border p-5 shadow">
                <div class="mb-3">
                    <%= documentaryfilm.label :name, "Nombre Documental:", class:"form-label" %>
                    <%= documentaryfilm.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= documentaryfilm.label :synopsis, "Sinopsis Documental:", class:"form-label" %>
                    <%= documentaryfilm.text_area :synopsis, class:"form-control" %>
                </div>
                <div class="mb-5">
                    <%= documentaryfilm.label :director, "Director Documental:", class:"form-label" %>
                    <%= documentaryfilm.text_field :director, class:"form-control" %>
                </div>
                <div>
                    <%= documentaryfilm.submit "Crear", class:"btn btn-dark" %>
                </div>
            </div>
        <%  end %>
    </div>
</div>
<div class="text-center my-5">
    <%= link_to "Listado Documental", documentaryfilms_index_path, class:"btn btn-dark" %>
    <%= link_to "Inicio", home_index_path, class:"btn btn-dark" %>
</div>

app/views/home/index.html.erb
<h1>Desafio - Almacenar Información</h1>
<p> Almacenar información en una base de datos </p>

    <div class="text-center my-5">
        <%= link_to "Crear Pelicula", movies_new_path, class:"btn btn-dark" %>
        <%= link_to "Crear Serie", shows_new_path, class:"btn btn-dark" %>
        <%= link_to "Crear Documental", documentaryfilms_new_path, class:"btn btn-dark" %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Almacenar Información</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <div class="container my-5">
    <%= yield %>
  </div>




    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Mostrando todos las Peliculas</h1>
<p>Cantidad de peliculas: <%= @movies.count %></p>

<% @movies.each do |movie| %>
    <h3><%= movie.name %></h3>
    <h3><%= movie.synopsis %></h3>
    <h3><%= movie.director %></h3>
<% end %>

<div>
    <%= link_to "Agregar nueva Pelicula", movies_new_path, class:"btn btn-dark" %>
</div>

app/views/movies/new.html.erb
<h1 class="text-center my-5">Crear Pelicula</h1>
<br><br>

<div class="d-flex justify-content-center">
    <div class="card col-6">
        <%= form_with model: @movie, method: :post do |movie| %>
            <div class="border p-5 shadow">
                <div class="mb-3">
                    <%= movie.label :name, "Nombre Pelicula:", class:"form-label" %>
                    <%= movie.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= movie.label :synopsis, "Sinopsis Pelicula:", class:"form-label" %>
                    <%= movie.text_area :synopsis, class:"form-control" %>
                </div>
                <div class="mb-5">
                    <%= movie.label :director, "Director Pelicula:", class:"form-label" %>
                    <%= movie.text_field :director, class:"form-control" %>
                </div>
                <div>
                    <%= movie.submit "Crear", class:"btn btn-dark" %>
                </div>
            </div>
        <%  end %>
    </div>
</div>
<div class="text-center my-5">
    <%= link_to "Listado Pelicula", movies_index_path, class:"btn btn-dark" %>
    <%= link_to "Inicio", home_index_path, class:"btn btn-dark" %>
</div>

app/views/shows/index.html.erb
<h1>Mostrando todas las Series</h1>
<p>Cantidad de series: <%= @shows.count %></p>

<% @shows.each do |show| %>
    <h3><%= show.name %></h3>
    <h3><%= show.synopsis %></h3>
    <h3><%= show.director %></h3>
<% end %>

<div>
    <%= link_to "Agregar nueva Serie", shows_new_path, class:"btn btn-dark" %>
</div>

app/views/shows/new.html.erb
<h1 class="text-center my-5">Crear Series</h1>
<br><br>

<div class="d-flex justify-content-center">
    <div class="card col-6">
        <%= form_with model: @show, method: :post do |show| %>
            <div class="border p-5 shadow">
                <div class="mb-3">
                    <%= show.label :name, "Nombre Serie:", class:"form-label" %>
                    <%= show.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= show.label :synopsis, "Sinopsis Serie:", class:"form-label" %>
                    <%= show.text_area :synopsis, class:"form-control" %>
                </div>
                <div class="mb-5">
                    <%= show.label :director, "Director Serie:", class:"form-label" %>
                    <%= show.text_field :director, class:"form-control" %>
                </div>
                <div>
                    <%= show.submit "Crear", class:"btn btn-dark" %>
                </div>
            </div>
        <%  end %>
    </div>
</div>
<div class="text-center my-5">
    <%= link_to "Listado Series", shows_index_path, class:"btn btn-dark" %>
    <%= link_to "Inicio", home_index_path, class:"btn btn-dark" %>
</div>